мой Youtube канал: https://www.youtube.com/results?search_query=%D0%B2%D0%B0%D0%BD%D1%8E%D1%85%D0%B0+%D0%BB%D0%B5%D0%B1%D0%B5%D0%B4%D0%B5%D0%B2 
Сайт я скоро выложу в общий доступ, а пока он доступен только мне!
Если вы не знали, что я делаю сайт, то теперь знайте.
